CREATE TABLE User (id INTEGER AUTO_INCREMENT NOT NULL, address1 VARCHAR(255), address2 VARCHAR(255), birthday DATE, email VARCHAR(255), headpic VARCHAR(255), name VARCHAR(255), notification_settings VARCHAR(255), password VARCHAR(255), phone VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE Message (id INTEGER AUTO_INCREMENT NOT NULL, details VARCHAR(255), state TINYINT(1) default 0, time DATETIME, type INTEGER, user_id INTEGER, PRIMARY KEY (id))
CREATE TABLE Task (id INTEGER AUTO_INCREMENT NOT NULL, begin_time DATETIME, description VARCHAR(255), finish_time DATETIME, status INTEGER, message_id INTEGER, project_id INTEGER, user_id INTEGER, PRIMARY KEY (id))
CREATE TABLE InitialDocument (id INTEGER AUTO_INCREMENT NOT NULL, description VARCHAR(255), edit_count INTEGER, newest_id INTEGER, path VARCHAR(255), title VARCHAR(255), upload_time DATETIME, version_id INTEGER, project_id INTEGER, user_id INTEGER, PRIMARY KEY (id))
CREATE TABLE Project (id INTEGER AUTO_INCREMENT NOT NULL, category VARCHAR(255), create_time DATETIME, description VARCHAR(255), due_time DATETIME, goal VARCHAR(255), modified_time DATETIME, name VARCHAR(255), owner INTEGER, PRIMARY KEY (id))
CREATE TABLE Copy (id INTEGER AUTO_INCREMENT NOT NULL, description VARCHAR(255), edit_count INTEGER, path VARCHAR(255), title VARCHAR(255), upload_time DATETIME, version_id INTEGER, belongs_to INTEGER, project_id INTEGER, user_id INTEGER, PRIMARY KEY (id))
CREATE TABLE MemberHistory (id INTEGER AUTO_INCREMENT NOT NULL, message INTEGER, time DATETIME, member_id INTEGER, project_id INTEGER, PRIMARY KEY (id))
CREATE TABLE ActionHistory (id INTEGER AUTO_INCREMENT NOT NULL, message VARCHAR(255), time DATETIME, project_id INTEGER, user_id INTEGER, PRIMARY KEY (id))
CREATE TABLE UploadedFile (id INTEGER AUTO_INCREMENT NOT NULL, description VARCHAR(255), ext VARCHAR(255), name VARCHAR(255), upload_time DATETIME, project_id INTEGER, user_id INTEGER, PRIMARY KEY (id))
CREATE TABLE Groupmember (user_id INTEGER NOT NULL, project_id INTEGER NOT NULL, PRIMARY KEY (user_id, project_id))
ALTER TABLE Message ADD CONSTRAINT FK_Message_user_id FOREIGN KEY (user_id) REFERENCES User (id)
ALTER TABLE Task ADD CONSTRAINT FK_Task_message_id FOREIGN KEY (message_id) REFERENCES Message (id)
ALTER TABLE Task ADD CONSTRAINT FK_Task_project_id FOREIGN KEY (project_id) REFERENCES Project (id)
ALTER TABLE Task ADD CONSTRAINT FK_Task_user_id FOREIGN KEY (user_id) REFERENCES User (id)
ALTER TABLE InitialDocument ADD CONSTRAINT FK_InitialDocument_user_id FOREIGN KEY (user_id) REFERENCES User (id)
ALTER TABLE InitialDocument ADD CONSTRAINT FK_InitialDocument_project_id FOREIGN KEY (project_id) REFERENCES Project (id)
ALTER TABLE Project ADD CONSTRAINT FK_Project_owner FOREIGN KEY (owner) REFERENCES User (id)
ALTER TABLE Copy ADD CONSTRAINT FK_Copy_project_id FOREIGN KEY (project_id) REFERENCES Project (id)
ALTER TABLE Copy ADD CONSTRAINT FK_Copy_belongs_to FOREIGN KEY (belongs_to) REFERENCES InitialDocument (id)
ALTER TABLE Copy ADD CONSTRAINT FK_Copy_user_id FOREIGN KEY (user_id) REFERENCES User (id)
ALTER TABLE MemberHistory ADD CONSTRAINT FK_MemberHistory_project_id FOREIGN KEY (project_id) REFERENCES Project (id)
ALTER TABLE MemberHistory ADD CONSTRAINT FK_MemberHistory_member_id FOREIGN KEY (member_id) REFERENCES User (id)
ALTER TABLE ActionHistory ADD CONSTRAINT FK_ActionHistory_project_id FOREIGN KEY (project_id) REFERENCES Project (id)
ALTER TABLE ActionHistory ADD CONSTRAINT FK_ActionHistory_user_id FOREIGN KEY (user_id) REFERENCES User (id)
ALTER TABLE UploadedFile ADD CONSTRAINT FK_UploadedFile_user_id FOREIGN KEY (user_id) REFERENCES User (id)
ALTER TABLE UploadedFile ADD CONSTRAINT FK_UploadedFile_project_id FOREIGN KEY (project_id) REFERENCES Project (id)
ALTER TABLE Groupmember ADD CONSTRAINT FK_Groupmember_user_id FOREIGN KEY (user_id) REFERENCES User (id)
ALTER TABLE Groupmember ADD CONSTRAINT FK_Groupmember_project_id FOREIGN KEY (project_id) REFERENCES Project (id)
